### ISSUE TITLE
fzf doesn't open file in normal mode (gvim/windows)

### ISSUE THREAD

**Issue by tuyenpm9** [junegunn/fzf#1169]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

_Environment: gvim8 patch 1-1358 / windows 10, compiled with +terminal._  

The issue: I have always press double ```<ESC>``` to exit `something unclear` to bring to normal mode in vim after select a file to open from fzf. Video [demo](https://drive.google.com/file/d/16r_tuo4ap9jwJCE_qzgs2IYQi068su5W/view?usp=sharing).  

I think terminal didn't exit properly so I asked in vim [here](https://github.com/vim/vim/issues/2400). I try to solve the issue by searching through fzf codebase but silly me I can't find anything.

**Comment by tuyenpm9** [comment]
The same result with only fzf plugin enabled:  
`gvim.exe -u NONE --cmd "set nocp | set rtp+=~/vimfiles/pack/plugins/start/fzf | runtime! plugin/fzf.vim"`

**Comment by junegunn** [comment]
Since https://github.com/gdamore/tcell/pull/159 (https://github.com/junegunn/fzf/issues/1093#issuecomment-339214145) is now merged, I'll rebuild Windows binary with the updated tcell and see if it helps.

**Comment by junegunn** [comment]
I can't reproduce ending up in insert mode, but I do need to press enter again to finish fzf process.

Updating tcell to the latest didn't help
- https://github.com/junegunn/fzf-bin/releases/download/alpha/fzf-0.17.2-alpha-windows_amd64.zip

**Comment by tuyenpm9** [comment]
It's not actually end up with insert mode but it didn't exit terminal cleanly. Right after open file I _can_ type characters into buffer. Thanks for looking into this issue.

**Comment by junegunn** [comment]
I have confirmed that the extra-enter problem is fixed with updated tcell. You can download the following alpha binary and test it.

https://github.com/junegunn/fzf-bin/releases/download/alpha/fzf-0.17.2-alpha-windows_amd64.zip

I first built fzf with the latest revision of tcell, but it didn't even run, panicking, so I had to update only to the point where the patch is merged, and all seemed fine.

**Comment by tuyenpm9** [comment]
Thanks. Do you notice that we have a gap between opened buffer and title of it? It keeps the title `!cmd.exe` for a while before change it to opened file. 

If I have this setup in minimal vimrc: `autocmd VimEnter * silent! :History<CR>`, the issue persist. Means the fix somehow happens after `autocmd` run.

**Comment by janlazo** [comment]
After `FZF` finishes execution on GVim, entering any key reverts the title to what it was before running `FZF`, or `History` in your autocmd. It's likely a lazy window update. IIRC, the Vim plugin doesn't modify `titlestring` or set the `term_name` in the Vim terminal options.

**Comment by tuyenpm9** [comment]
@janlazo : Is there a way to make it faster to update title on current buffer?
Can you confirm the issue still happens with this setup?
Minimal vimrc:
```autocmd VimEnter * silent! :History<CR>```  
- Run this command in cmd under user directory:
```gvim.exe --cmd "set nocp | set rtp+=~/vimfiles/pack/plugins/start/fzf | runtime! plugin/fzf.vim"```
- Open an arbitrary file and immediately type something right after open the file. You'll see that characters put into the file. We expect it should open the file in normal mode.

**Comment by janlazo** [comment]
```viml
call term_start('cmd', {'curwin': v:true, 'term_finish': 'close'})
```

acts like `:terminal ++close` and should force the update but the exit callback must be updated. It works for me on `8.0.1358`.
Otherwise, try `:normal` and feed any `hjkl` movement characters.

**Comment by tuyenpm9** [comment]
> call term_start('cmd', {'curwin': v:true, 'term_finish': 'close'})
>
Thanks this works for me. https://github.com/junegunn/fzf/pull/1172

**Comment by tuyenpm9** [comment]
Sorry I tested combination of two PR #1172 and #1173. Just need #1173 to make update title work instantly.  
Don't know on other systems.

**Comment by tuyenpm9** [comment]
But the issue about normal mode still happens https://github.com/junegunn/fzf/issues/1169#issuecomment-348872060

**Comment by janlazo** [comment]
I can reproduce the normal mode issue with your autocmd but I don't know why it happens.

**Comment by tuyenpm9** [comment]
Thanks, I have to stop invoke `:History` at vim startup. Hope this issue be fixed soon. If possible please open the issue so someone may has solution for it.

**Comment by tuyenpm9** [comment]
The normal open issue with autocmd persist with version fzf  0.17.3.

**Comment by junegunn** [comment]
I don't have access to Windows machine now, so I'm not sure, but does this help?

```vim
autocmd VimEnter * silent! :redraw! | History<CR>
```

And you mean it only happens when you trigger the command on VimEnter event?

**Comment by tuyenpm9** [comment]
Sorry but it doesn't work.
Yes, I have another map that trigger manually after vim started: `nnoremap <silent> <leader>s :History<CR>` and it didn't have normal issue, `:History` also doesn't have normal isue.

**Comment by tuyenpm9** [comment]
I've noticed something that maybe help on this. I can produce a weird behavior happens when issue commands `:History` or `:FZF` then press ```<C-c>``` two times, it will produce a message:  
`Type       :qa!     and press <Enter> to abandon all changes and exit Vim`   
The expected behavior should be press ```<C-c>``` one time and fall back to current buffer.
