### ISSUE TITLE
fzf hangs inside of vim inside of GNU screen when started in detached mode

### ISSUE THREAD

**Issue by georgevpanayotov** [junegunn/fzf#1427]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [X] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

Those are the categories under which I reproduced the problem. It may occur in others.
Repro steps:

install the latest fzf for zsh and vim
$ screen -d -m -S "name_scr"
$ screen -rx name_scr

# within the screen:
$ vim

# within vim
:FZF

# EXPECTED 
does the whole FZF thing

# ACTUAL
Hangs until I run:
$ killall -9 fzf

# NOTES
I removed all of my shell configs to make sure it wasn't something my configs were doing.
This doesn't occur in a second window within the same screen (i.e. started via ctrl-A C)

**Comment by LuRsT** [comment]
Hi @georgevpanayotov,

since it's been a while since this happened, have you figured out what the problem was, or is it fixed now?

**Comment by georgevpanayotov** [comment]
No, I haven't figured out the problem. It still seems to happen but I haven't synced to a newer version of fzf.

**Comment by LuRsT** [comment]
Try it out and let us know :+1: . Would be also worth it to know if it only happens in a specific directory or not.

Alternatively, try running vim with strace and check what happens:

```
$ strace -o log.log vim
<inside vim>
:FZF
```

kill it, inspect `log.log` for something out of the ordinary.

**Comment by georgevpanayotov** [comment]
I updated and still experienced the issue. I tried strace and noticed it was stuck in a poll loop. This stanza kept recurring:

```poll([{fd=3, events=POLLIN}], 1, 0)     = 0 (Timeout)
nanosleep({0, 10000000}, NULL)          = 0
wait4(2604, 0x7ffe41cfdabc, WNOHANG, NULL) = 0
recvmsg(3, 0x7ffe41cfd7a0, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7ffe41cfd7a0, 0)           = -1 EAGAIN (Resource temporarily unavailable)```

Attached:
[log.log](https://github.com/junegunn/fzf/files/4273412/log.log)

**Comment by georgevpanayotov** [comment]
Any updates on this? Any other info I can provide?

**Comment by junegunn** [comment]
I have not been able to reproduce the problem you described.
- Does fzf work outside of Vim in that window?
- Which version of Vim are you running? Have you tried upgrading it to the latest?

**Comment by georgevpanayotov** [comment]
Recently followed up on this after updating fzf on my machine. Seems like it's not an issue any longer.
